FILE_PARAM:
  PAGE_NAME: 'Bill phone numbers'
  PATH_TO_FILE_OUT: 'W:\IT\MTS_BILLING\OUT\result.xlsx'
  PATH_TO_IN_FOLDER: 'W:\IT\MTS_BILLING\IN\'

#FILE_PARAM: - Общая секция настроек
#  PAGE_NAME: - Название страницы
#  PATH_TO_FILE_OUT: 'полный путь и название файла excel'
#  PATH_TO_IN_FOLDER: 'Полный путь к каталогу с входными файлами'