FILE_PARAM:
  PAGE_NAME: 'Bill phone numbers'
  PATH_TO_FILE_OUT: 'W:\IT\maxim.nalimov\PROJECTS\MTS BILLING REPORT\OUT\result.xlsx'
  PATH_TO_IN_FOLDER: 'W:\IT\maxim.nalimov\PROJECTS\MTS BILLING REPORT\IN\'
